version: 0.0
os: linux
files:
- source: /
  destination: /apps/webapp
hooks:
  BeforeInstall:
    - location: deployment.js
      timeout: 180
  AfterInstall:
    - location: deployment.js
      timeout: 180
  ApplicationStart:
    - location: deployment.js
      timeout: 180
  ValidateService:
    - location: deployment.js
      timeout: 180
