version: 0.0
os: linux

files:
- source: /
  destination: /home/ubuntu/webapp
permissions:
- object: /home/ubuntu
  owner: ubuntu
  group: ubuntu
  type:
  - directory
  - file

hooks:
  BeforeInstall:
  - location: scripts/install.sh
    timeout: 300
    runas: root
  ApplicationStart:
  - location: scripts/run.sh
    timeout: 120
    runas: ubuntu
  - location: scripts/nginx.sh
    timeout: 120
    runas: root
  ApplicationStop:
  - location: scripts/stop.sh
    timeout: 120
    runas: ubuntu
  ValidateService:
  - location: scripts/validate.sh
    timeout: 60
    runas: ubuntu
