
CREATE TABLE IF NOT EXISTS `articles` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL DEFAULT '',
  `content` text NOT NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM;
