import Head from "next/head";
import Image from "next/image";
import { excuteQuery } from "../lib/db";
import styles from "../styles/Home.module.css";

export async function getServerSideProps() {
  const { articles, error } = await excuteQuery("SELECT * FROM articles", []);

  return {
    props: {
      error,
      articles: articles.map((article) => ({
        id: article.id,
        title: article.title,
        content: article.content,
        date: article.date.toJSON(),
      })),
    },
  };
}

export default function Home({ error, articles }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Koala AWS App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <Image
            src="/koala_badge.png"
            alt="Koala"
            width="150"
            height="150"
            unoptimized={true}
          />
          <br />
          Welcome to <b>Koala AWS APP</b>
        </h1>

        {error ? (
          <p className={styles.description}>
            <code className={styles.code}>{error}</code>
          </p>
        ) : (
          <>
            <p className={styles.description}>
              We have
              <code className={styles.code}>{articles.length} articles</code>!
            </p>

            <div className={styles.grid}>
              {articles.map((article) => (
                <a
                  key={article.id}
                  href="https://nextjs.org/docs"
                  className={styles.card}
                >
                  <h2>{article.title}</h2>
                  <p>{article.content}</p>
                  <time>{article.date}</time>
                </a>
              ))}
            </div>
          </>
        )}
      </main>
    </div>
  );
}
